# This is a basic workflow to help you get started with Actions

name: Deploying Azure Resource group

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

Lint:
 name: RunBicepLinter
 runs-on : ubuntu-latest
 steps:
  -uses: action/checkout@v3
  -name: Create Output Directory
   run:|
     mkdir -p ${{ github.workspace }}/src/bicep/File
 
  -name: Azure-login
   uses: azure/login@v1
   with:
      creds: ${{ secrets.MY_SECRET 

  -name: Rub Bicep Linter
    working-directory: '${{github.workspace}}/src/bicep'
    run:|
       az bicep build --file ./ResourceGroup.Bice --outdir ./File
       ls ./File
    
     
     
   
